name: Java CI

on: [pull_request]

jobs:
  build:
    name: CheckStatus
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Run Tests
        run: mvn --batch-mode --update-snapshots test
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
